### ISSUE TITLE
Make SF and OSDN storage or projects configurable

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-iso-action#13]
Currently we are fixed to `manjaro` as OSDN storage and `manjarolinux` as SF project. We should make that a variable as we have more projects or storage folders for these.

**Comment by philmmanjaro** [comment]
For SF we have:

```
rsync -vaP --stats -e ssh ${{ steps.upload-prepare.outputs.upload-files }} \
          ${{ inputs.sf-user }}@frs.sourceforge.net:/home/frs/project/${{ inputs.sf-project }}/${{ inputs.edition }}/${{ inputs.version }}/
```
... which is fine. We only have to add that to the README properly.

For OSDN we have:

```
rsync -vaP --stats -e ssh ${{ steps.upload-prepare.outputs.upload-files }} \
          ${{ inputs.osdn-user }}@storage.osdn.net:/storage/groups/m/ma/${{ inputs.osdn-project }}/${{ inputs.edition }}/${{ inputs.version }}/
```
Since it uploads to groups we have hardcoded `m/ma` which might not work for a project like `archlinux`. It would be `a/ar`. So we need to cut the letters from the `${{ inputs.osdn-project }}` as needed to make it work.

**Comment by boredland** [comment]
>  We only have to add that to the README properly.

wdym? its already in the readme.. do you think we need to be more clear about a variable being.. variable?
