### ISSUE TITLE
[Feature] Add GPG signing using Github Secrets

### ISSUE THREAD

**Issue by Strit** [manjaro/manjaro-iso-action#2]
The current implementation looks awesome.

Borrowed some stuff for our ARM builds.

But I noticed it does not have GPG signing of the ISO files.
I tried getting this work, but was not successful. See: https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

I tried adding it, but it just resolves in empty variables for me.

**Comment by boredland** [comment]
hey! in my eyes machine signing with gpg is of questionable value - however I added it in PR #1. not in the complicated "interactive" passphrase entering version, but assuming a non-protected base64 encoded secret. would that be enough for you?

**Comment by Strit** [comment]
The signing key we use, have a passphrase.

**Comment by boredland** [comment]
but why.. its merely the difference of loading 1 or 2 secrets from the same secret storage. On the other hand you could just remove the passphare using `gpg --edit-key <keyid>` (setting it to nothing). If you insist, I'll do it. But I really don't see why we should.

**Comment by boredland** [comment]
never mind, it was easy enough to add, so I just did that.
