### ISSUE TITLE
ISO build failing through Github Actions

### ISSUE THREAD

**Issue by unkemptArc99** [manjaro/manjaro-iso-action#28]
Hi,

I was following the tutorial at https://www.youtube.com/watch?v=S2t5Iat37CI on building custom Manjaro ISO images. My main motivation for building the image was to test the latest 5.16 kernel in the Live USB environment (particularly, to test whether the new Realtek rtw89 driver works with my Realtek 8852 AE card).

Here is my repository - https://github.com/unkemptArc99/iso-build, and here are the failed release jobs - https://github.com/unkemptArc99/iso-build/actions/runs/1695615140 (I tried to run all possible combinations in the matrix to see whether the error that I recieve was just a one-off).

The changes that I made to the iso_build.yml file (which controls the action of building the ISO) is -
1. change the kernel to `linux-516`
2. change the matrix to have all the possible combinations of manjaro flavors.

The consistent error that I am facing is the following - 
```
  -> Copying mhwd package cache ...
==> ERROR: File '/var/lib/manjaro-tools/buildiso/xfce/x86_64/mhwdfs/opt/mhwd/pkg/*pkg.tar*' not found.
==> ERROR: A failure occurred in make_image_mhwd().
    Aborting...
```
and after this even the rollback step fails -
```
Run echo *** | gh auth login --with-token
  echo *** | gh auth login --with-token
  gh release delete 202201140103 -y --repo unkemptArc99/iso-build
  shell: /usr/bin/bash -e {0}
release not found
Error: Process completed with exit code 1.
```

Is this a genuine error OR am I just a terrible noob and completely doing this wrong?

Thanks in advance!

**Comment by boredland** [comment]
The real issue here is "error: target not found: linux516-zfs". This module does not yet exist, so you can't build for kernel 5.16. Just wait a few more days, I guess.
