### ISSUE TITLE
arch-install-script broken

### ISSUE THREAD

**Issue by bittin** [manjaro/manjaro-iso-action#3]
Hello!

The Arch-install-script link has been broken since Saturday 26th June as the Arch Linux People has moved things around so there has been no Manjaro builds for 3 days

Run pkgver=24
--2021-06-28 05:46:22--  https://github.com/archlinux/arch-install-scripts/archive/refs/tags/v.tar.gz
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/archlinux/arch-install-scripts/tar.gz/refs/tags/v [following]
--2021-06-28 05:46:22--  https://codeload.github.com/archlinux/arch-install-scripts/tar.gz/refs/tags/v
Resolving codeload.github.com (codeload.github.com)... 140.82.114.9
Connecting to codeload.github.com (codeload.github.com)|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-28 05:46:22 ERROR 404: Not Found.

Error: Process completed with exit code 8.  

[1]: https://github.com/archlinux/arch-install-scripts/releases/tag/v24
[2]: https://gitlab.archlinux.org/archlinux/infrastructure/-/issues/6
[3]: https://lists.archlinux.org/pipermail/arch-dev-public/2021-June/030469.html

**Comment by boredland** [comment]
can you point me to the action that fails? this seems to work fine in this action so my guess is, that the action you're talking about (and "pkgver=24" is a relatively clear indication) is not yet pointing to this action.

**Comment by bittin** [comment]
@philmmanjaro @pheiduck @boredland 

https://github.com/bittin/iso-build/actions/runs/977879644 
https://github.com/bittin/iso-build/blob/main/.github/workflows/iso_build.yml

**Comment by boredland** [comment]
yeah, this action will replace 90% percent of your iso-build workflow. you can just adapt it to look like this: https://github.com/Manjaro-Sway/manjaro-sway/blob/feat/shorter_iso_action/.github/workflows/iso_build.yaml

**Comment by boredland** [comment]
It will not work fully tho until we merged the outstanding PR.

**Comment by bittin** [comment]
> It will not work fully tho until we merged the outstanding PR.

Yep now it crashed again: https://github.com/bittin/iso-build/runs/2929770656 

Can you ping me here when it should work? and i can try again

**Comment by boredland** [comment]
> > It will not work fully tho until we merged the outstanding PR.
> 
> Yep now it crashed again but somewhere else: https://github.com/bittin/iso-build/runs/2929770656 
> 
> Can you ping me here when it should work? and i can try again 

Hm, it shouldn't fail tho. I think you're pointing to the Manjaro sway iso profile. You'll have to adapt the parameters of the action to what you want to build ;-)

**Comment by boredland** [comment]
Ah, and you should remove virtually everything else.

**Comment by pheiduck** [comment]
Here is my untested solution:
https://github.com/pheiduck/iso-build/blob/main/.github/workflows/iso_build_linux510.yml

**Comment by bittin** [comment]
> > > It will not work fully tho until we merged the outstanding PR.
> > 
> > 
> > Yep now it crashed again but somewhere else: https://github.com/bittin/iso-build/runs/2929770656
> > Can you ping me here when it should work? and i can try again
> 
> Hm, it shouldn't fail tho. I think you're pointing to the Manjaro sway iso profile. You'll have to adapt the parameters of the action to what you want to build ;-)

Silly me forgot to change to my awesome repo URL: https://github.com/bittin/iso-profiles/tree/master/community/awesome 
Testing again now

**Comment by bittin** [comment]
> Here is my untested solution:
> https://github.com/pheiduck/iso-build/blob/main/.github/workflows/iso_build_linux510.yml

https://github.com/bittin/iso-build/runs/2930101256
that failed :(

**Comment by bittin** [comment]
Got a working build now: https://github.com/bittin/iso-build/runs/2930527436 

Thanks for all the help :)
