### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by Maverik0071** [manjaro/manjaro-iso-action#31]
Folllwed the iso-build tutorial on Youtube and now I am having this issue:

Not working :(
"cannot stat 'pacman.conf.x86_64': No such file or directory"

**Comment by boredland** [comment]
no idea what video you talk about. also please provide a reproduction repo.

**Comment by boredland** [comment]
Your repo seems to be private:
![image](https://user-images.githubusercontent.com/4662748/163054107-fec34eb8-10ea-49d2-9dbe-580b3d557f5f.png)

**Comment by Maverik0071** [comment]
It's now public..sorry about that

**Comment by boredland** [comment]
the [readme](https://github.com/manjaro/manjaro-iso-action) has a working example, also this repo has a [working example](https://github.com/manjaro/manjaro-iso-action/blob/main/.github/workflows/test.yml) as a test. you can also find [here](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/.github/workflows/iso_build.yaml) how I use it on manjaro sway (bit modified to automatically determine the kernel versions etc).

**Comment by Maverik0071** [comment]
Oh okay well I'll use it as an example and see where I went wrong.  Thank you and if I have any more issues I'll let you know.  I greatly appreciate it.  I'll have something good to always say about the Manjaro devs.
