### ISSUE TITLE
How long to build and distribute Manjaro via Github Actions?

### ISSUE THREAD

**Issue by playgithub** [manjaro/manjaro-iso-action#40]
If every run of an action needs to build manjaro first, the time to build manjaro matters.

**Comment by boredland** [comment]
I don't understand this question. This action is meant to build an iso of the distribution. The time that takes, you can look up in recent runs.

**Comment by playgithub** [comment]
There are many actions, which one is for manjaro iso?

**Comment by boredland** [comment]
This is the github action. It is being used in lots of places. The prominent one is [release-preview](https://github.com/manjaro/release-review/actions). Apparently there it takes around 1h to build and distribute a new manjaro iso. For [manjaro sway](https://github.com/manjaro-sway/manjaro-sway/actions) it is a bit shorter with around 40 minutes.

**Comment by playgithub** [comment]
Thanks
