### ISSUE TITLE
Add upload features to CDN77, OSDN and SF

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-iso-action#6]
For our public releases we upload to CDN77 and SF as of now. We may add that also to the action.

https://github.com/manjaro/citestbed/blob/master/.github/workflows/iso_build.yaml

Also each upload should be configurable. Like if I do official ISOs I don't need a split ISO, only GH needs that. So we have to find a way to have GH supported and schedule that upload after SF or CDN77 and OSDN.

**Comment by boredland** [comment]
Shouldn't we then make separate actions for those Uploads? Since if you want to set up each of those, you'll need additional secrets etc.

**Comment by boredland** [comment]
And: shouldn't we always do a github release by default since it doesn't require any configuration? The .iso still exists if you want to upload it in a next step.

**Comment by philmmanjaro** [comment]
GH releases make sense for people not pushing it to SF or other hoster. The ISO split is only needed for GH. And yes you may need extra secretes to make it work. Code is given and if we make it optional we can maintain one action instead of several. We can do a session about it to get into more details. For now I can do another action and we see on how we merge it.
