### ISSUE TITLE
Default yaml file copied from readme fails with tag v2.9

### ISSUE THREAD

**Issue by CrystalSpore** [manjaro/manjaro-iso-action#67]
Using just the default config file, build fails with `patch: **** Can't open patch file ../pacman-sync-first-option.patch : No such file or directory`

Link to build step with error: https://github.com/CrystalSpore/manjaro_iso_build/actions/runs/10584048784/job/29327394116#step:3:2220

**Comment by boredland** [comment]
There are many outdated things, starting with the linux version, in that README. We're always using the latest version in manjaro-sway, perhaps you could take that as an inspiration: https://github.com/manjaro-sway/manjaro-sway/blob/main/.github/workflows/build.yaml

**Comment by CrystalSpore** [comment]
I referenced the main releases instead of sway instead (doing amd64 build & not aarch64), & got much further. The build completed but there was an issue adding it to the GitHub release. I'll work to troubleshoot this on my end. (I'm also now trying to use the source forge upload, just to see if that is easier to manage)

**Comment by CrystalSpore** [comment]
Seems that the iso build is completing, but even though on the previous output I see "release exists", on the next line it says "release not found":

https://github.com/CrystalSpore/manjaro_matsutake/actions/runs/10618574864/job/29434152891#step:3:8062

**Comment by CrystalSpore** [comment]
This last part was my fault. Seems that I had to change the default permissions to allow full write access with the default GitHub token, as shown below

![Screenshot_20240830-154119.png](https://github.com/user-attachments/assets/a0da3ff3-f20f-4cbe-9426-0e3a31713070)

It might be worth adjusting the workflow to set the required [permissions level](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token) to follow best token practices, but I'm unsure if that would be handled in this repo or in each user's repo that is implementing the workflow
